version: "3"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Fortaleza
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8500:80
      - 8600:443
    restart: unless-stopped