version: '3.8'
services:
    jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
        - "49160:8080"
        - "49159:50000"
      container_name: jenkins
      volumes:
        - /home/matheus/jenkins/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - devops

    nexus:
      image: sonatype/nexus
      container_name: nexus
      ports:
        - "8081:8081"
      volumes:
        - "/opt/nexus/:/var/lib/nexus"
      networks:
        - devops

    sonarqube:
      image: sonarqube:community
      hostname: sonarqube
      container_name: sonarqube
      depends_on:
        - db
      environment:
        SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
        SONAR_JDBC_USERNAME: sonar
        SONAR_JDBC_PASSWORD: sonar
      volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs
      ports:
        - "9000:9000"
      networks:
        - devops
    db:
      image: postgres:13
      hostname: postgresql
      container_name: postgresql
      environment:
        POSTGRES_USER: sonar
        POSTGRES_PASSWORD: sonar
        POSTGRES_DB: sonar
      volumes:
        - postgresql:/var/lib/postgresql
        - postgresql_data:/var/lib/postgresql/data
      networks:
        - devops
networks:
  devops:
    external: true

volumes:
  jenkins_home:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: