version: '3.8'
services:
    jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
        - "49160:8080"
        - "49159:50000"
      container_name: jenkins
      volumes:
        - /home/matheus/jenkins/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock