name: Terraform Validation

on: [push]

env:
  TERRAFORM_VERSION: 1.3.7

jobs:
  terraform_validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl

    - name: Install Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    - name: Update TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Validate Terraform Code
      run: |
        terraform init
        tflint
        echo "TFLint output: $(tflint)"
        terraform validate

    - name: Final Output
      run: |
        echo "TFLint Output: $(tflint)"
        echo "Terraform code is valid. Pipeline completed successfully!"
