http:
 #region routers
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox

    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole

    pihole2:
      entryPoints:
        - "https"
      rule: "Host(`pihole2.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole2

    pihole3:
      entryPoints:
        - "https"
      rule: "Host(`pihole3.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole3

    piholevip:
      entryPoints:
        - "https"
      rule: "Host(`piholevip.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: piholevip
    
    teamcity:
      entryPoints:
        - "https"
      rule: "Host(`teamcity.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: teamcity

    jenkins:
      entryPoints:
        - "https"
      rule: "Host(`jenkins.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: jenkins

    jnlp:
      entryPoints:
        - "https"
      rule: "Host(`jnlp-jenkins.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: jnlp

    nexus:
      entryPoints:
        - "https"
      rule: "Host(`nexus.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: nexus
    
    qube:
      entryPoints:
        - "https"
      rule: "Host(`qube.yourlocaldomain.com)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: qube

    grafana:
      entryPoints:
        - "https"
      rule: "Host(`grafana.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: grafana
    
    influxdb:
      entryPoints:
        - "https"
      rule: "Host(`influxdb.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: influxdb

    heimdall:
      entryPoints:
        - "https"
      rule: "Host(`heimdall.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: heimdall   
    
    uptime-kuma:
      entryPoints:
        - "https"
      rule: "Host(`uptimekuma.yourlocaldomain.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: uptimekuma 

#endregion
#region services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.0.60.2:8006"
        passHostHeader: true

    pihole:
      loadBalancer:
        servers:
          - url: "http://10.0.60.3"
        passHostHeader: true

    pihole2:
      loadBalancer:
        servers:
          - url: "http://10.0.60.53"
        passHostHeader: true

    pihole3:
      loadBalancer:
        servers:
          - url: "http://10.0.60.20"
        passHostHeader: true
    
    piholevip:
      loadBalancer:
        servers:
          - url: "http://10.0.60.100"
        passHostHeader: true
    
    heimdall:
      loadBalancer:
        servers:
          - url: "http://10.0.60.4:8500/"
        passHostHeader: true
    
    influxdb:
      loadBalancer:
        servers:
          - url: "http://10.0.60.4:8086"
        passHostHeader: true

    grafana:
      loadBalancer:
        servers:
          - url: "http://10.0.60.4:3000"
        passHostHeader: true

    teamcity:
      loadBalancer:
        servers:
          - url: "http://10.0.60.5:8111"
        passHostHeader: true

    jenkins:
      loadBalancer:
        servers:
          - url: "http://10.0.60.5:49160"
        passHostHeader: true
    
    jnlp:
      loadBalancer:
        servers:
          - url: "http://10.0.60.5:49159"
        passHostHeader: true

    nexus:
      loadBalancer:
        servers:
          - url: "http://10.0.60.5:8081"
        passHostHeader: true

    qube:
      loadBalancer:
        servers:
          - url: "http://10.0.60.5:9000"
        passHostHeader: true

    uptimekuma:
      loadBalancer:
        servers:
          - url: "http://10.0.60.4:3001"
        passHostHeader: true

#endregion
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin/"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
        