version: '3'

services:
    traefik:
        image: traefik:latest

        container_name: traefik

        restart: unless-stopped

        security_opt:
            - no-new-privileges:true

        networks:
            - proxy

        ports:
            - 80:80
            - 443:443

        environment:
            # Be sure to use the correct one depending on if you are using a token or key
            - CF_API_EMAIL=dnsprovideremail@exemple.com
            - CF_DNS_API_TOKEN=dnsprovider-api-token
            #- CF_API_KEY=dnsprovider-api-key

        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data/traefik.yml:/traefik.yml:ro
            - ./data/acme.json:/acme.json
            - ./config.yml:/config.yml:ro

        labels:

            - "traefik.enable=true"
            - "traefik.http.routers.traefik.entrypoints=http"
            - "traefik.http.routers.traefik.rule=Host(`traefik.yourlocaldomain.com`)"
            - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:BASIC_AUTH_PASSWORD"
            - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
            - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
            - "traefik.http.routers.traefik-secure.entrypoints=https"
            - "traefik.http.routers.traefik-secure.rule=Host(`traefik.yourlocaldomain.com`)"
            - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
            - "traefik.http.routers.traefik-secure.tls=true"
            - "traefik.http.routers.traefik-secure.tls.certresolver=***YOURDNSPROVIDER***"
            - "traefik.http.routers.traefik-secure.tls.domains[0].main=yourlocaldomain.com"
            - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.yourlocaldomain.com"
            - "traefik.http.routers.traefik-secure.service=api@internal"
           
networks:
  proxy:
   external: true
