pipeline {
    agent any
    tools{
        terraform 'terraform'
    }
    environment {
        GITHUB_TOKEN = credentials('github_token')
    }
    
    stages {
            stage('Clone Repository') {
                steps {
                    git branch: 'main', credentialsId: 'github_token', url: 'https://github.com/mthsfrts/Terraform.git'
                }
            }
            stage("Terraform Init"){
                steps {
                    //Remote backend
                    // sh 'terraform init -backend-config="proxmox.token=055f87ac-1ed0-4dcb-a204-695eed50ac46" -backend-config="proxmox.url=https://10.0.60.2:8006/api2/json" -backend-config="proxmox.datacenter=home-cluster" -backend-config="proxmox.node=lab"'
                    
                    //Local backend
                    sh 'terraform init'
                }      
            }
            stage('Validate') {
                steps {
                    sh 'terraform validate'
                }
            }
            stage('Terraform Plan') {
                // when {
                //     expression { !currentBuild.isInProgress() && currentBuild.previousBuild.result == 'SUCCESS' }
                // }
                steps {
                    script {
                        def tf_plan = sh (script: 'terraform plan -out=tfplan', returnStdout: true)
                        if(tf_plan.contains("No changes")) {
                            currentBuild.result = 'ABORTED'
                            echo "No changes detected, skipping apply"
                            error("No changes detected, skipping apply")
                        }
                    }
                }
            }
            stage('Terraform Apply') {
                when {
                    expression { currentBuild.result != 'ABORTED' && currentBuild.result == 'SUCCESS' }
                }
                steps {
                    echo "Starting Terraform apply"
                    script {
                        def tf_apply = sh (script: 'terraform apply -auto-approve tfplan', returnStdout: true)
                        if(tf_apply.contains("Error")) {
                            currentBuild.result = 'FAILURE'
                            error("Error occurred during apply stage")
                    } 
                        else {
                            echo "Apply stage completed successfully"
                    }
                }
            }
        }
    }
}

