pipeline {
    agent any
    stages {
        stage("Clone Git repository") {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/branch']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    submoduleCfg: [],
                    userRemoteConfigs: [[
                        credentialsId: 'your-jenkins-id-credential',
                        url: 'git@github.com:username/repo.git'
                    ]]
                ])
            }
        }
        stage("Install dependencies") {
            steps {
                sh 'apt-get update'
                sh 'apt-get install -y wget curl'
            }
        }
        stage('Install Terraform') {
            steps {
                sh 'wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip'
                sh 'unzip terraform_1.3.7_linux_amd64.zip'
                sh 'mv terraform /usr/local/bin/'
            }
        }
        stage('Update TFLint') {
            steps {
                sh 'curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash'
            }
        }
        stage('Validate Terraform Code') {
            steps {
                sh 'terraform init'
                sh 'tflint'
                sh 'terraform validate'
            }
        }
        stage('Final Output') {
            steps {
                echo 'Terraform code is valid. Pipeline completed successfully!'
            }
        }
    }
}

